### PR TITLE
Fix bug #88

### PR DESCRIPTION
**Pull request by Marthijs-Berfelo**
Fix for #88
changed long condition for parts.size, to be 5 or 6.
made minor improvements to make better use of kotlin language functionality.

### CODE REVIEW

**Comment by Marthijs-Berfelo** [comment]
@fwcd or @georgewfraser  please review and merge if ok

**Comment by fwcd** [comment]
Coincidentally I fixed this particular issue a few minutes ago in c65b415. I have your stylistic changes into 92d3969 though.

**Comment by Marthijs-Berfelo** [comment]
Great! you've even added more artifact information, I've added comments to [c65b415](https://github.com/fwcd/KotlinLanguageServer/commit/c65b415e7ccbdaf19072e0df750cdf81cdff61e0) with some opportunities to improve / make use of Kotlin language.
Hope it helps

**Comment by Marthijs-Berfelo** [comment]
When can we expect a new release?

**Pull request closed without merging**
