### PR TITLE
WIP: Gradle 5 and Java 11 support

### PR DESCRIPTION
**Pull request by fwcd**
This PR tracks support for Gradle 5 and Java 11.

### CODE REVIEW

**Comment by fwcd** [comment]
Unfortunately, support for Kotlin scripts is broken due to some breaking API changes in the script declaration resolver. For more details, see the commit message on 4df20d4.

**Comment by mattdkerr** [comment]
Is this still true for kotlin `1.3.40`?

**Comment by casret** [comment]
I see this was merged, how do I build the server under 11?

**Comment by fwcd** [comment]
@casret Just as before, using `./gradlew :server:installDist` or `./gradlew :server:build`. Note that even if you use JDK 11/12, the compiler will still target JVM 8 byte code (for compatibility reasons). This should run fine on higher JDKs though.

**Pull request merged**
